var menudata={children:[
{text:"Programmer's Guide",url:"usergroup0.html",children:[
{text:"Building",url:"flatbuffers_guide_building.html"},
{text:"Tutorial",url:"flatbuffers_guide_tutorial.html"},
{text:"Using the schema compiler",url:"flatbuffers_guide_using_schema_compiler.html"},
{text:"Writing a schema",url:"flatbuffers_guide_writing_schema.html"},
{text:"Use in C++",url:"flatbuffers_guide_use_cpp.html"},
{text:"Use in C",url:"flatbuffers_guide_use_c.html"},
{text:"Use in Go",url:"flatbuffers_guide_use_go.html"},
{text:"Use in Java/C#",url:"flatbuffers_guide_use_java_c-sharp.html"},
{text:"Use in JavaScript",url:"flatbuffers_guide_use_javascript.html"},
{text:"Use in TypeScript",url:"@ref flatbuffers_guide_use_typescript"},
{text:"Use in PHP",url:"flatbuffers_guide_use_php.html"},
{text:"Use in Python",url:"flatbuffers_guide_use_python.html"},
{text:"Schema-less version",url:"flexbuffers.html"},
{text:"gRPC",url:"usergroup1.html",children:[
{text:"Use in C++",url:"flatbuffers_grpc_guide_use_cpp.html"}]}]},
{text:"Platform / Language / Feature support",url:"flatbuffers_support.html"},
{text:"Benchmarks",url:"flatbuffers_benchmarks.html"},
{text:"FlatBuffers white paper",url:"flatbuffers_white_paper.html"},
{text:"FlatBuffers internals",url:"flatbuffers_internals.html"},
{text:"Grammar of the schema language",url:"flatbuffers_grammar.html"},
{text:"API Reference",url:"usergroup2.html",children:[
{text:"APIs",url:"modules.html"},
{text:"Class List",url:"annotated.html",children:[
{text:"Class List",url:"annotated.html"},
{text:"Class Index",url:"classes.html"},
{text:"Class Hierarchy",url:"hierarchy.html"},
{text:"Class Members",url:"functions.html",children:[
{text:"All",url:"functions.html",children:[
{text:"$",url:"functions.html#index_0x24"},
{text:"_",url:"functions.html#index__"},
{text:"a",url:"functions.html#index_a"},
{text:"c",url:"functions.html#index_c"},
{text:"d",url:"functions.html#index_d"},
{text:"e",url:"functions.html#index_e"},
{text:"f",url:"functions.html#index_f"},
{text:"g",url:"functions.html#index_g"},
{text:"i",url:"functions.html#index_i"},
{text:"k",url:"functions.html#index_k"},
{text:"n",url:"functions.html#index_n"},
{text:"o",url:"functions.html#index_o"},
{text:"p",url:"functions.html#index_p"},
{text:"r",url:"functions.html#index_r"},
{text:"s",url:"functions.html#index_s"}]},
{text:"Functions",url:"functions_func.html",children:[
{text:"_",url:"functions_func.html#index__"},
{text:"a",url:"functions_func.html#index_a"},
{text:"c",url:"functions_func.html#index_c"},
{text:"d",url:"functions_func.html#index_d"},
{text:"e",url:"functions_func.html#index_e"},
{text:"f",url:"functions_func.html#index_f"},
{text:"g",url:"functions_func.html#index_g"},
{text:"i",url:"functions_func.html#index_i"},
{text:"n",url:"functions_func.html#index_n"},
{text:"o",url:"functions_func.html#index_o"},
{text:"p",url:"functions_func.html#index_p"},
{text:"r",url:"functions_func.html#index_r"},
{text:"s",url:"functions_func.html#index_s"}]},
{text:"Variables",url:"functions_vars.html"},
{text:"Properties",url:"functions_prop.html"}]}]}]},
{text:"Contributing",url:"contributing.html"}]}
